apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-env-helmchart
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/santosh-gh/k8s-20-deployment.git
          revision: HEAD
          directories:
          - path: multi-environment-helmchart/*
      - list:
          elements:
          - env: dev
          - env: test
          - env: prod
  template:
    metadata:
      name: '{{path.basename}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/santosh-gh/k8s-20-deployment.git
        targetRevision: HEAD
        path: 'multi-environment-helmchart/{{path.basename}}'
        helm:
          valueFiles:
            - '{{env}}-values.yaml'
      destination:
        server:  https://kubernetes.default.svc
        namespace:  '{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true